/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-02 at 22:28:59 UTC 
 * Modify at your own risk.
 */

package de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model;

/**
 * Model definition for Quest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the questendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Quest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String accessCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String author;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Point> pointList;

  static {
    // hack to force ProGuard to consider Point used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Point.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer questId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccessCode() {
    return accessCode;
  }

  /**
   * @param accessCode accessCode or {@code null} for none
   */
  public Quest setAccessCode(java.lang.String accessCode) {
    this.accessCode = accessCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthor() {
    return author;
  }

  /**
   * @param author author or {@code null} for none
   */
  public Quest setAuthor(java.lang.String author) {
    this.author = author;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Quest setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Quest setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Point> getPointList() {
    return pointList;
  }

  /**
   * @param pointList pointList or {@code null} for none
   */
  public Quest setPointList(java.util.List<Point> pointList) {
    this.pointList = pointList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQuestId() {
    return questId;
  }

  /**
   * @param questId questId or {@code null} for none
   */
  public Quest setQuestId(java.lang.Integer questId) {
    this.questId = questId;
    return this;
  }

  @Override
  public Quest set(String fieldName, Object value) {
    return (Quest) super.set(fieldName, value);
  }

  @Override
  public Quest clone() {
    return (Quest) super.clone();
  }

}
