/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-02 at 22:28:59 UTC 
 * Modify at your own risk.
 */

package de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint;

/**
 * Service definition for Questendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link QuestendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Questendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the questendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://mc-schnitzeljagd-2013.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "questendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Questendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Questendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getQuest".
   *
   * This request holds the parameters needed by the the questendpoint server.  After setting any
   * optional parameters, call the {@link GetQuest#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetQuest getQuest(java.lang.Long id) throws java.io.IOException {
    GetQuest result = new GetQuest(id);
    initialize(result);
    return result;
  }

  public class GetQuest extends QuestendpointRequest<de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest> {

    private static final String REST_PATH = "quest/{id}";

    /**
     * Create a request for the method "getQuest".
     *
     * This request holds the parameters needed by the the questendpoint server.  After setting any
     * optional parameters, call the {@link GetQuest#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetQuest#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetQuest(java.lang.Long id) {
      super(Questendpoint.this, "GET", REST_PATH, null, de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetQuest setAlt(java.lang.String alt) {
      return (GetQuest) super.setAlt(alt);
    }

    @Override
    public GetQuest setFields(java.lang.String fields) {
      return (GetQuest) super.setFields(fields);
    }

    @Override
    public GetQuest setKey(java.lang.String key) {
      return (GetQuest) super.setKey(key);
    }

    @Override
    public GetQuest setOauthToken(java.lang.String oauthToken) {
      return (GetQuest) super.setOauthToken(oauthToken);
    }

    @Override
    public GetQuest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetQuest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetQuest setQuotaUser(java.lang.String quotaUser) {
      return (GetQuest) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetQuest setUserIp(java.lang.String userIp) {
      return (GetQuest) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetQuest setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetQuest set(String parameterName, Object value) {
      return (GetQuest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertQuest".
   *
   * This request holds the parameters needed by the the questendpoint server.  After setting any
   * optional parameters, call the {@link InsertQuest#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest}
   * @return the request
   */
  public InsertQuest insertQuest(de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest content) throws java.io.IOException {
    InsertQuest result = new InsertQuest(content);
    initialize(result);
    return result;
  }

  public class InsertQuest extends QuestendpointRequest<de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest> {

    private static final String REST_PATH = "quest";

    /**
     * Create a request for the method "insertQuest".
     *
     * This request holds the parameters needed by the the questendpoint server.  After setting any
     * optional parameters, call the {@link InsertQuest#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertQuest#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest}
     * @since 1.13
     */
    protected InsertQuest(de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest content) {
      super(Questendpoint.this, "POST", REST_PATH, content, de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest.class);
    }

    @Override
    public InsertQuest setAlt(java.lang.String alt) {
      return (InsertQuest) super.setAlt(alt);
    }

    @Override
    public InsertQuest setFields(java.lang.String fields) {
      return (InsertQuest) super.setFields(fields);
    }

    @Override
    public InsertQuest setKey(java.lang.String key) {
      return (InsertQuest) super.setKey(key);
    }

    @Override
    public InsertQuest setOauthToken(java.lang.String oauthToken) {
      return (InsertQuest) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertQuest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertQuest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertQuest setQuotaUser(java.lang.String quotaUser) {
      return (InsertQuest) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertQuest setUserIp(java.lang.String userIp) {
      return (InsertQuest) super.setUserIp(userIp);
    }

    @Override
    public InsertQuest set(String parameterName, Object value) {
      return (InsertQuest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listQuest".
   *
   * This request holds the parameters needed by the the questendpoint server.  After setting any
   * optional parameters, call the {@link ListQuest#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListQuest listQuest() throws java.io.IOException {
    ListQuest result = new ListQuest();
    initialize(result);
    return result;
  }

  public class ListQuest extends QuestendpointRequest<de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.CollectionResponseQuest> {

    private static final String REST_PATH = "quest";

    /**
     * Create a request for the method "listQuest".
     *
     * This request holds the parameters needed by the the questendpoint server.  After setting any
     * optional parameters, call the {@link ListQuest#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListQuest#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListQuest() {
      super(Questendpoint.this, "GET", REST_PATH, null, de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.CollectionResponseQuest.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListQuest setAlt(java.lang.String alt) {
      return (ListQuest) super.setAlt(alt);
    }

    @Override
    public ListQuest setFields(java.lang.String fields) {
      return (ListQuest) super.setFields(fields);
    }

    @Override
    public ListQuest setKey(java.lang.String key) {
      return (ListQuest) super.setKey(key);
    }

    @Override
    public ListQuest setOauthToken(java.lang.String oauthToken) {
      return (ListQuest) super.setOauthToken(oauthToken);
    }

    @Override
    public ListQuest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListQuest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListQuest setQuotaUser(java.lang.String quotaUser) {
      return (ListQuest) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListQuest setUserIp(java.lang.String userIp) {
      return (ListQuest) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListQuest setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListQuest setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListQuest set(String parameterName, Object value) {
      return (ListQuest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeQuest".
   *
   * This request holds the parameters needed by the the questendpoint server.  After setting any
   * optional parameters, call the {@link RemoveQuest#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveQuest removeQuest(java.lang.Long id) throws java.io.IOException {
    RemoveQuest result = new RemoveQuest(id);
    initialize(result);
    return result;
  }

  public class RemoveQuest extends QuestendpointRequest<Void> {

    private static final String REST_PATH = "quest/{id}";

    /**
     * Create a request for the method "removeQuest".
     *
     * This request holds the parameters needed by the the questendpoint server.  After setting any
     * optional parameters, call the {@link RemoveQuest#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveQuest#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveQuest(java.lang.Long id) {
      super(Questendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveQuest setAlt(java.lang.String alt) {
      return (RemoveQuest) super.setAlt(alt);
    }

    @Override
    public RemoveQuest setFields(java.lang.String fields) {
      return (RemoveQuest) super.setFields(fields);
    }

    @Override
    public RemoveQuest setKey(java.lang.String key) {
      return (RemoveQuest) super.setKey(key);
    }

    @Override
    public RemoveQuest setOauthToken(java.lang.String oauthToken) {
      return (RemoveQuest) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveQuest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveQuest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveQuest setQuotaUser(java.lang.String quotaUser) {
      return (RemoveQuest) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveQuest setUserIp(java.lang.String userIp) {
      return (RemoveQuest) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveQuest setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveQuest set(String parameterName, Object value) {
      return (RemoveQuest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateQuest".
   *
   * This request holds the parameters needed by the the questendpoint server.  After setting any
   * optional parameters, call the {@link UpdateQuest#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest}
   * @return the request
   */
  public UpdateQuest updateQuest(de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest content) throws java.io.IOException {
    UpdateQuest result = new UpdateQuest(content);
    initialize(result);
    return result;
  }

  public class UpdateQuest extends QuestendpointRequest<de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest> {

    private static final String REST_PATH = "quest";

    /**
     * Create a request for the method "updateQuest".
     *
     * This request holds the parameters needed by the the questendpoint server.  After setting any
     * optional parameters, call the {@link UpdateQuest#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateQuest#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest}
     * @since 1.13
     */
    protected UpdateQuest(de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest content) {
      super(Questendpoint.this, "PUT", REST_PATH, content, de.hsb.kss.mc_schnitzeljagd.persistence.questendpoint.model.Quest.class);
    }

    @Override
    public UpdateQuest setAlt(java.lang.String alt) {
      return (UpdateQuest) super.setAlt(alt);
    }

    @Override
    public UpdateQuest setFields(java.lang.String fields) {
      return (UpdateQuest) super.setFields(fields);
    }

    @Override
    public UpdateQuest setKey(java.lang.String key) {
      return (UpdateQuest) super.setKey(key);
    }

    @Override
    public UpdateQuest setOauthToken(java.lang.String oauthToken) {
      return (UpdateQuest) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateQuest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateQuest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateQuest setQuotaUser(java.lang.String quotaUser) {
      return (UpdateQuest) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateQuest setUserIp(java.lang.String userIp) {
      return (UpdateQuest) super.setUserIp(userIp);
    }

    @Override
    public UpdateQuest set(String parameterName, Object value) {
      return (UpdateQuest) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Questendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Questendpoint}. */
    @Override
    public Questendpoint build() {
      return new Questendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link QuestendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setQuestendpointRequestInitializer(
        QuestendpointRequestInitializer questendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(questendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
